image:
  file: .gitpod.dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:

  - name: API Server
    init: |
      pip install wheel
      pip install -r requirements/dev.txt
    command: |
      cp .gitpod.env .env.local
      sed -i "s~CHAOSGENIUS_WEBAPP_URL_HERE~`gp url 5000`~g" ".env.local"
      pg_start
      flask db upgrade
      unset PGHOSTADDR
      bash dev_server.sh

  - name: Webapp
    init: |
      cd frontend
      npm install
    command: |
      cd frontend
      REACT_APP_BASE_URL=`gp url 5000` npm start

  - name: Redis
    command: redis-server

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-browser
    visibility: "public"
  - port: 5000
    visibility: "public"

vscode:
  extensions:
    - "ms-python.python"
    - "samuelcolvin.jinjahtml"
